export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR';
export const FETCH_WEATHER_PROGRESS = 'FETCH_WEATHER_PROGRESS';
export const FETCH_WEATHER_CLEAR_API_STATE = 'FETCH_WEATHER_CLEAR_API_STATE';
